/**
 * Backtest data loaders — reads from locally pre-fetched JSON files.
 * Files are generated by running: node scripts/fetchBacktestData.mjs
 * No external API calls — works in any environment (local, Vercel, sandbox).
 */

import { readFileSync, existsSync, readdirSync } from 'fs'
import { join } from 'path'
import type { OhlcBar } from '@/lib/quant/technicals'

export interface OhlcvRow extends OhlcBar {
  time: number // Unix seconds
  volume: number
}

export interface DataFile {
  ticker: string
  sector: string
  fetchedAt: string
  candles: OhlcvRow[]
}

// Path to the pre-fetched data directory (relative to project root)
function dataDir(): string {
  return join(process.cwd(), 'scripts', 'backtestData')
}

/**
 * Read a pre-fetched JSON data file for a given ticker.
 * Returns null if file doesn't exist (ticker not pre-fetched yet).
 */
export function loadLocalData(ticker: string): DataFile | null {
  const safe = ticker.replace(/\./g, '-')  // BRK.B → BRK-B
  const filePath = join(dataDir(), `${safe}.json`)
  if (!existsSync(filePath)) return null
  try {
    const raw = readFileSync(filePath, 'utf-8')
    return JSON.parse(raw) as DataFile
  } catch {
    return null
  }
}

/**
 * Load daily OHLCV history for a stock ticker from pre-fetched local JSON.
 * Returns empty array if data file not found.
 */
export function loadStockHistory(ticker: string): OhlcvRow[] {
  const data = loadLocalData(ticker)
  if (!data) return []
  const out: OhlcvRow[] = []
  for (const c of data.candles) {
    if (
      Number.isFinite(c.time) &&
      Number.isFinite(c.open) &&
      Number.isFinite(c.high) &&
      Number.isFinite(c.low) &&
      Number.isFinite(c.close)
    ) {
      out.push({ time: c.time, open: c.open, high: c.high, low: c.low, close: c.close, volume: c.volume ?? 0 })
    }
  }
  return out
}

/**
 * Load daily BTC/USD OHLCV from pre-fetched local JSON.
 * Returns empty array if data file not found.
 */
export function loadBtcHistory(): OhlcvRow[] {
  const data = loadLocalData('BTC')
  if (!data) return []
  const out: OhlcvRow[] = []
  for (const c of data.candles) {
    if (
      Number.isFinite(c.time) &&
      Number.isFinite(c.open) &&
      Number.isFinite(c.high) &&
      Number.isFinite(c.low) &&
      Number.isFinite(c.close)
    ) {
      out.push({ time: c.time, open: c.open, high: c.high, low: c.low, close: c.close, volume: c.volume ?? 0 })
    }
  }
  return out
}

/**
 * Get the list of all tickers that have pre-fetched data.
 */
export function availableTickers(): string[] {
  const dir = dataDir()
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace(/\.json$/, '').replace(/-/g, '.'))  // BRK-B → BRK.B
}

/** Convert OhlcvRow[] to close price array. */
export function closesFromRows(rows: OhlcvRow[]): number[] {
  return rows.map((r) => r.close)
}

/** Convert OhlcvRow[] to OhlcBar[] (strip time/volume). */
export function barsFromRows(rows: OhlcvRow[]): OhlcBar[] {
  return rows.map(({ open, high, low, close }) => ({ open, high, low, close }))
}
