/**
 * Q-075 mutation-hardening GOLDEN tests (2026-07-16).
 *
 * The 2026-07-12 Stryker run scored lib/backtest at 31.22 — the existing
 * suites assert structure and bounds, which arithmetic/conditional mutants
 * sail through. These tests pin EXACT numeric outputs of the engines on
 * deterministic synthetic fixtures, so any mutation of the accounting,
 * annualization, cost, windowing, or scoring math shifts a pinned value.
 *
 * The pinned values are CHARACTERIZATION goldens generated by running these
 * exact fixtures through the shipped implementation. If an INTENDED behavior
 * change moves them, update the pins from the failure diff in the same
 * commit — a silent drift is exactly what these tests exist to catch.
 *
 * Feature flag: the engine goldens run with QUANTAN_USE_ENHANCED_SIGNAL=0
 * (the PRODUCTION signal path — regime-only); enhanced-path pins stub it on.
 */
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import {
  backtestInstrument,
  computeBuyAndHoldReturn,
  tradingDaysPerYear,
  TX_COST_PCT_PER_SIDE,
} from '@/lib/backtest/core'
import type { OhlcvRow } from '@/lib/backtest/core'
import { runPortfolioBacktest } from '@/lib/backtest/portfolioBacktest'
import { DEFAULT_EXIT_CONFIG } from '@/lib/backtest/exitRules'
import { enhancedCombinedSignal, resolveBacktestSignal } from '@/lib/backtest/signals'
import {
  walkForwardAnalysis,
  walkForwardSummary,
  computeOosRatio,
} from '@/lib/backtest/walkForward'
import { buildLiveInstrumentSignal, REGIME_COLORS } from '@/lib/backtest/liveSignal'
import { runInstrumentLabelBenchmark, signalAtBarIndex } from '@/lib/backtest/benchmarkLabel'
import {
  piecewiseRsiScore,
  isGoldenCross,
  hasPositiveMomentum,
  detectBullishDivergence,
  detectVolumeClimax,
  isMACompression,
  priceWasNearSmaRecently,
} from '@/lib/backtest/signalHelpers'

// ─── Deterministic fixtures (shared with the golden generator) ──────────────

const SECONDS_PER_DAY = 86400
const START_TIME = Date.UTC(2024, 0, 1) / 1000

function makeOhlcv(bars: number, priceFn: (i: number) => number, range = 0.5): OhlcvRow[] {
  const out: OhlcvRow[] = []
  for (let i = 0; i < bars; i++) {
    const close = priceFn(i)
    const open = i === 0 ? close : priceFn(i - 1)
    out.push({
      time: START_TIME + i * SECONDS_PER_DAY,
      open,
      high: Math.max(open, close) + range,
      low: Math.min(open, close) - range,
      close,
      volume: 1_000_000 + (i % 7) * 50_000,
    })
  }
  return out
}

/**
 * Exp uptrend at `rate`/bar with single-bar crashes (level ×= crashFactor) at
 * each bar in `crashes`; growth continues from the crashed level at
 * `tailRate`/bar after the FIRST crash (tailRate defaults to rate).
 */
function multiDipSeries(
  bars: number,
  crashes: number[],
  rate = 0.004,
  crashFactor = 0.64,
  tailRate?: number,
): OhlcvRow[] {
  const closes: number[] = []
  let level = 100
  let g = rate
  const crashSet = new Set(crashes)
  for (let i = 0; i < bars; i++) {
    if (i > 0) level *= 1 + g
    if (crashSet.has(i)) {
      level *= crashFactor
      g = tailRate ?? rate
    }
    closes.push(level)
  }
  return makeOhlcv(bars, (i) => closes[i], 0.2)
}

const dipRecover380 = () => multiDipSeries(380, [300], 0.004, 0.64, 0.005)
const dipLoss380 = () => multiDipSeries(380, [300], 0.004, 0.64, -0.003)
const dipBar301 = () => multiDipSeries(301, [300]) // last bar IS the crash bar

function sigInputs(rows: OhlcvRow[]) {
  const closes = rows.map((r) => r.close)
  const bars = rows.map(({ open, high, low, close }) => ({ open, high, low, close }))
  const ohlcv = rows.map((r) => ({
    open: r.open, high: r.high, low: r.low, close: r.close,
    volume: r.volume ?? 0, time: r.time,
  }))
  return { closes, bars, ohlcv, price: closes[closes.length - 1] }
}

afterEach(() => {
  vi.unstubAllEnvs()
})

// ─── core.backtestInstrument — production (regime-only) path goldens ────────

describe('backtestInstrument — golden run (production signal path)', () => {
  beforeEach(() => vi.stubEnv('QUANTAN_USE_ENHANCED_SIGNAL', '0'))

  it('WIN scenario: crash then +0.5%/bar recovery — exact accounting', () => {
    const res = backtestInstrument('AAPL', 'Technology', dipRecover380())
    expect(res.totalTrades).toBe(1)
    expect(res.totalReturn).toBeCloseTo(0.01604, 5)
    expect(res.annualizedReturn).toBeCloseTo(0.010609, 5)
    expect(res.sharpeRatio).toBeCloseTo(-5.736055, 4)
    expect(res.sortinoRatio).toBeCloseTo(-7.902196, 4)
    expect(res.maxDrawdown).toBeCloseTo(0.000163, 5)
    expect(res.winRate).toBe(1)
    expect(res.profitFactor).toBe(Infinity) // one win, zero losses
    expect(res.avgTradeReturn).toBeCloseTo(0.11042, 5)
    expect(res.confidenceAvg).toBe(90)
    expect(res.equityCurve).toHaveLength(180)
    expect(res.bnhCurve).toHaveLength(180)
    expect(res.dailyReturns).toHaveLength(179)
    expect(res.bnhReturn).toBeCloseTo(2.143494, 5)
    // excessReturn is DEFINED as totalReturn - bnhReturn
    expect(res.excessReturn).toBeCloseTo(res.totalReturn - res.bnhReturn, 10)

    const t = res.closedTrades[0]
    expect(t.date).toBe('2024-10-27')
    expect(t.entryPrice).toBeCloseTo(211.979477, 5)
    expect(t.exitPrice).toBeCloseTo(235.386263, 5)
    expect(t.shares).toBe(70)
    expect(t.pnlPct).toBeCloseTo(0.11042, 5)
    expect(t.confidence).toBe(90)
    // pnlPct is the raw price move by definition
    expect(t.pnlPct).toBeCloseTo((t.exitPrice - t.entryPrice) / t.entryPrice, 10)
  })

  it('LOSS scenario: crash then −0.3%/bar decline — exact accounting', () => {
    const res = backtestInstrument('AAPL', 'Technology', dipLoss380())
    expect(res.totalTrades).toBe(1)
    expect(res.totalReturn).toBeCloseTo(-0.00939, 5)
    expect(res.annualizedReturn).toBeCloseTo(-0.006237, 5)
    expect(res.sharpeRatio).toBeCloseTo(-25.669592, 3)
    expect(res.sortinoRatio).toBeCloseTo(-13.511796, 3)
    expect(res.maxDrawdown).toBeCloseTo(0.00939, 5)
    expect(res.winRate).toBe(0)
    expect(res.profitFactor).toBe(0)
    expect(res.avgTradeReturn).toBeCloseTo(-0.061145, 5)
    expect(res.bnhReturn).toBeCloseTo(0.671904, 5)
    const t = res.closedTrades[0]
    expect(t.entryPrice).toBeCloseTo(211.979477, 5)
    expect(t.exitPrice).toBeCloseTo(199.017901, 5)
    expect(t.pnlPct).toBeCloseTo(-0.061145, 5)
  })

  it('crypto annualization (365d) shifts annualized return + Sharpe on identical rows', () => {
    const res = backtestInstrument('BTC', 'Crypto', dipRecover380())
    expect(res.totalTrades).toBe(1)
    expect(res.annualizedReturn).toBeCloseTo(0.015402, 5) // vs 0.010609 at 252d
    expect(res.sharpeRatio).toBeCloseTo(-2.645719, 4) // vs -5.736055 at 252d
  })

  it('win/loss classification is NET of round-trip costs (F-4 boundary)', () => {
    // A trade whose raw pnl is inside (0, 2×cost] must classify as a LOSS.
    // The WIN golden above has pnl 11% >> 22bps, so winRate=1 pins the net
    // rule from the other side; here we pin the constant itself.
    expect(TX_COST_PCT_PER_SIDE).toBeCloseTo(0.0011, 10)
  })
})

describe('backtestInstrument — enhanced path (flag on) golden', () => {
  beforeEach(() => vi.stubEnv('QUANTAN_USE_ENHANCED_SIGNAL', '1'))

  it('enhanced confluence filters the recovery-dip BUY entirely (0 trades)', () => {
    const res = backtestInstrument('AAPL', 'Technology', dipRecover380())
    expect(res.totalTrades).toBe(0)
    expect(res.totalReturn).toBe(0)
    expect(res.sharpeRatio).toBeNull()
    expect(res.sortinoRatio).toBeCloseTo(-15.874508, 4)
    expect(res.bnhReturn).toBeCloseTo(2.143494, 5)
    expect(res.confidenceAvg).toBe(0)
  })
})

describe('computeBuyAndHoldReturn + tradingDaysPerYear — exact pins', () => {
  it('reinvests the ex-date dividend at that bar close', () => {
    const rows: OhlcvRow[] = [
      { time: START_TIME, open: 100, high: 101, low: 99, close: 100, volume: 1 },
      { time: START_TIME + SECONDS_PER_DAY, open: 100, high: 105, low: 99, close: 104, volume: 1, dividend: 2 },
      { time: START_TIME + 2 * SECONDS_PER_DAY, open: 104, high: 111, low: 103, close: 110, volume: 1 },
    ]
    // shares = 1 + 2/104; final = shares × 110; return = final/100 − 1
    expect(computeBuyAndHoldReturn(rows)).toBeCloseTo(0.121154, 6)
    expect(computeBuyAndHoldReturn(rows.slice(0, 1))).toBe(0)
  })

  it('365d for known crypto tickers and crypto sector, 252d otherwise', () => {
    expect(tradingDaysPerYear('btc', '')).toBe(365) // case-insensitive ticker
    expect(tradingDaysPerYear('AAPL', 'Crypto')).toBe(365) // sector match
    expect(tradingDaysPerYear('AAPL', 'Technology')).toBe(252)
  })
})

// ─── runPortfolioBacktest — production path goldens ─────────────────────────

const portfolioData = () => ({
  AA: multiDipSeries(460, [300, 380], 0.004, 0.64, 0.005),
  BB: multiDipSeries(460, [320, 400], 0.0035, 0.7, -0.003),
})
const portfolioSectors = { AA: 'Technology', BB: 'Healthcare' }

describe('runPortfolioBacktest — golden run (production signal path)', () => {
  beforeEach(() => vi.stubEnv('QUANTAN_USE_ENHANCED_SIGNAL', '0'))

  it('label-matched default: 4 time-only exits, exact P&L accounting', () => {
    const res = runPortfolioBacktest(portfolioData(), portfolioSectors)
    expect(res.totalTrades).toBe(4)
    expect(res.finalCapital).toBeCloseTo(101467.949045, 2)
    expect(res.totalReturn).toBeCloseTo(0.014679, 5)
    expect(res.winRate).toBeCloseTo(0.5, 10)
    expect(res.avgTradeReturn).toBeCloseTo(0.022386, 5)
    expect(res.maxDrawdown).toBeCloseTo(0.016919, 5)
    expect(res.maxConcurrentPositions).toBe(2)
    expect(res.avgConcurrentPositions).toBeCloseTo(0.182609, 5)
    expect(res.equityCurve).toHaveLength(241)
    expect(res.dailyReturns).toHaveLength(240)
    expect(res.sharpeRatio).toBeCloseTo(-5.21958, 3)
    expect(res.sortinoRatio).toBeCloseTo(-5.939125, 3)
    expect(res.varMetrics.var95_1d).toBeCloseTo(0.000437, 5)
    expect(res.varMetrics.var99_1d).toBeNull() // < 250 daily returns

    // D2/D4: time_exit is the ONLY position-level exit under the default.
    expect(res.exitReasonBreakdown).toEqual({
      signal: 0, stop_loss: 0, time_exit: 4,
      profit_target: 0, panic_exit: 0, max_drawdown: 0, end_of_data: 0,
    })

    expect(res.sectorAttribution.Technology.trades).toBe(2)
    expect(res.sectorAttribution.Technology.winRate).toBe(1)
    expect(res.sectorAttribution.Technology.avgReturn).toBeCloseTo(0.10798, 5)
    expect(res.sectorAttribution.Healthcare.trades).toBe(2)
    expect(res.sectorAttribution.Healthcare.winRate).toBe(0)
    expect(res.sectorAttribution.Healthcare.avgReturn).toBeCloseTo(-0.063209, 5)

    const t0 = res.trades[0]
    expect(t0.ticker).toBe('AA')
    expect(t0.entryDate).toBe('2024-10-27')
    expect(t0.exitDate).toBe('2024-11-17') // exactly 20 union bars later
    expect(t0.entryPrice).toBeCloseTo(211.979477, 5)
    expect(t0.exitPrice).toBeCloseTo(235.386263, 5)
    expect(t0.shares).toBe(70)
    expect(t0.exitReason).toBe('time_exit')
    // pnlPct is net of BOTH per-side costs (D2-2 netPnlPctFromPrices)
    const c = TX_COST_PCT_PER_SIDE
    const entryAllIn = t0.entryPrice * (1 + c)
    const exitNet = t0.exitPrice * (1 - c)
    expect(t0.pnlPct).toBeCloseTo((exitNet - entryAllIn) / entryAllIn, 10)
    expect(t0.pnlPct).toBeCloseTo(0.10798, 5)
  })

  it('legacy DEFAULT_EXIT_CONFIG re-arms stops/targets/panic/signal exits', () => {
    const res = runPortfolioBacktest(portfolioData(), portfolioSectors, {
      exit: DEFAULT_EXIT_CONFIG,
    })
    expect(res.totalTrades).toBe(8)
    expect(res.finalCapital).toBeCloseTo(101563.621183, 2)
    expect(res.winRate).toBeCloseTo(0.625, 10)
    expect(res.exitReasonBreakdown).toEqual({
      signal: 2, stop_loss: 1, time_exit: 1,
      profit_target: 1, panic_exit: 3, max_drawdown: 0, end_of_data: 0,
    })
  })

  it('empty instrument map returns the exact empty result', () => {
    const res = runPortfolioBacktest({}, {})
    expect(res.finalCapital).toBe(res.initialCapital)
    expect(res.totalTrades).toBe(0)
    expect(res.equityCurve).toEqual([res.initialCapital])
    expect(res.varMetrics).toEqual({ var95_1d: null, var99_1d: null })
  })
})

// ─── enhancedCombinedSignal — exact score pins ───────────────────────────────

describe('enhancedCombinedSignal — exact per-indicator score pins', () => {
  it('dip bar (FIRST_DIP/STRONG_DIP): every score and weighted score', () => {
    const { closes, bars, ohlcv, price } = sigInputs(dipBar301())
    const s = enhancedCombinedSignal('TST', '2026-01-01', price, closes, bars, ohlcv)
    expect(s.action).toBe('HOLD')
    expect(s.confidence).toBe(90)
    expect(s.KellyFraction).toBeCloseTo(0.1, 10)
    expect(s.totalWeightedScore).toBeCloseTo(-0.033333, 5)
    expect(s.regime.zone).toBe('FIRST_DIP')
    expect(s.regime.dipSignal).toBe('STRONG_DIP')
    expect(s.multiTfScore).toBe(-2)
    const scores = s.weightedConfirms.map((c) => c.score)
    const expected = [1, -1, -1, 1, 0.8, -0.666667, -0.8]
    expected.forEach((e, i) => expect(scores[i]).toBeCloseTo(e, 5))
    const wscores = s.weightedConfirms.map((c) => c.weightedScore)
    const expectedW = [0.2, -0.15, -0.1, 0.15, 0.08, -0.133333, -0.08]
    expectedW.forEach((e, i) => expect(wscores[i]).toBeCloseTo(e, 5))
    // ensemble identity: total = Σ weightedScore (no bonuses without gates)
    const sum = s.weightedConfirms.reduce((a, c) => a + c.weightedScore, 0)
    expect(s.totalWeightedScore).toBeCloseTo(sum, 10)
  })

  it('exponential uptrend (EXTREME_BULL/OVERBOUGHT): pure-math pins', () => {
    const rows = makeOhlcv(300, (i) => 100 * Math.pow(1.004, i), 0.2)
    const { closes, bars, ohlcv, price } = sigInputs(rows)
    const s = enhancedCombinedSignal('TST', '2026-01-01', price, closes, bars, ohlcv)
    expect(s.action).toBe('HOLD')
    expect(s.confidence).toBe(44)
    expect(s.regime.zone).toBe('EXTREME_BULL')
    expect(s.regime.dipSignal).toBe('OVERBOUGHT')
    // RSI/MACD/ATR/BB scores are pure closes/bars arithmetic — pin exactly.
    // The Vol-POC zone score on THIS fixture sits on a volume-profile bin
    // boundary (1-ulp Math.pow differences flip it across Node versions —
    // observed 2026-07-16, Node 20 CI vs Node 25 local), so the zone-coupled
    // components and the total are asserted structurally instead.
    const scores = s.weightedConfirms.map((c) => c.score)
    ;[-1, 0.815495, 0.499981, -0.812534].forEach((e, i) => expect(scores[i]).toBeCloseTo(e, 5))
    scores.forEach((v) => expect(Math.abs(v)).toBeLessThanOrEqual(1))
    // Ensemble identity always holds: total = Σ weightedScore (no gate bonuses)
    const sum = s.weightedConfirms.reduce((a, c) => a + c.weightedScore, 0)
    expect(s.totalWeightedScore).toBeCloseTo(sum, 10)
    // Below the 0.25 BUY threshold on every runtime seen (0.119–0.149)
    expect(s.totalWeightedScore).toBeGreaterThan(0)
    expect(s.totalWeightedScore).toBeLessThan(0.25)
  })

  it('falling knife (CRASH_ZONE): SELL with Kelly 1.0 and exact pins', () => {
    const rows = makeOhlcv(300, (i) => (i < 250 ? 100 + i * 0.1 : 125 - (i - 250) * 1.2), 0.2)
    const { closes, bars, ohlcv, price } = sigInputs(rows)
    const s = enhancedCombinedSignal('TST', '2026-01-01', price, closes, bars, ohlcv)
    expect(s.action).toBe('SELL')
    expect(s.confidence).toBe(95)
    expect(s.KellyFraction).toBe(1.0)
    expect(s.totalWeightedScore).toBeCloseTo(-0.050023, 5)
    expect(s.regime.zone).toBe('CRASH_ZONE')
    expect(s.regime.dipSignal).toBe('FALLING_KNIFE')
    const scores = s.weightedConfirms.map((c) => c.score)
    const expected = [1, -1, -0.436458, 0.802897, 0.8, -0.666667, 0.5]
    expected.forEach((e, i) => expect(scores[i]).toBeCloseTo(e, 5))
  })

  it('sector threshold overrides move the BUY/SELL cut lines', () => {
    const { closes, bars, ohlcv, price } = sigInputs(dipBar301())
    // Base dip bar is HOLD at tws ≈ -0.0333. A sell threshold ABOVE that
    // score must flip the HOLD to SELL; the default (-0.30) must not.
    const flipped = enhancedCombinedSignal('TST', '2026-01-01', price, closes, bars, ohlcv, {}, {
      sellWScoreThreshold: -0.01,
    })
    expect(flipped.action).toBe('SELL')
    const held = enhancedCombinedSignal('TST', '2026-01-01', price, closes, bars, ohlcv, {}, {
      sellWScoreThreshold: -0.30,
    })
    expect(held.action).toBe('HOLD')
  })
})

// ─── resolveBacktestSignal — flag branch pins ────────────────────────────────

describe('resolveBacktestSignal — feature-flag branches', () => {
  it('flag OFF: regime-only path with exact Kelly/confidence pass-through', () => {
    vi.stubEnv('QUANTAN_USE_ENHANCED_SIGNAL', '0')
    const { closes, bars, ohlcv, price } = sigInputs(dipBar301())
    const s = resolveBacktestSignal('TST', '2026-01-01', price, closes, bars, ohlcv)
    expect(s.action).toBe('BUY')
    expect(s.confidence).toBe(90)
    expect(s.KellyFraction).toBeCloseTo(0.15, 10) // halfKelly default
    expect(s.totalWeightedScore).toBe(0)
    expect(s.confirms).toEqual([])
    expect(s.weightedConfirms).toEqual([])
    expect(s.multiTfScore).toBe(0)
    expect(s.volumeZone).toBeNull()
    expect(s.reason).toBe('FIRST_DIP [regime-only path; enhanced disabled in production]')
    expect(s.regime.zone).toBe('FIRST_DIP')
  })

  it('flag OFF + halfKelly false doubles the BUY Kelly to 0.30', () => {
    vi.stubEnv('QUANTAN_USE_ENHANCED_SIGNAL', '0')
    const { closes, bars, ohlcv, price } = sigInputs(dipBar301())
    const s = resolveBacktestSignal('TST', '2026-01-01', price, closes, bars, ohlcv, { halfKelly: false })
    expect(s.KellyFraction).toBeCloseTo(0.30, 10)
  })

  it('flag ON: delegates verbatim to enhancedCombinedSignal', () => {
    vi.stubEnv('QUANTAN_USE_ENHANCED_SIGNAL', '1')
    const { closes, bars, ohlcv, price } = sigInputs(dipBar301())
    const viaResolver = resolveBacktestSignal('TST', '2026-01-01', price, closes, bars, ohlcv)
    const direct = enhancedCombinedSignal('TST', '2026-01-01', price, closes, bars, ohlcv)
    expect(viaResolver.action).toBe(direct.action)
    expect(viaResolver.totalWeightedScore).toBeCloseTo(direct.totalWeightedScore, 12)
    expect(viaResolver.confidence).toBe(direct.confidence)
    expect(viaResolver.weightedConfirms).toHaveLength(7)
    expect(viaResolver.reason).toBe(direct.reason)
  })
})

// ─── walkForward — window + summary goldens ──────────────────────────────────

describe('walkForward — golden windows (production signal path)', () => {
  beforeEach(() => vi.stubEnv('QUANTAN_USE_ENHANCED_SIGNAL', '0'))

  const wfRows = () => multiDipSeries(700, [300, 420, 540], 0.004, 0.64, 0.005)

  it('3 windows with exact boundaries, returns, Sharpes, and ratio clamp', () => {
    const wins = walkForwardAnalysis('AAPL', 'Technology', wfRows())
    expect(wins).toHaveLength(3)

    expect(wins[0].periodLabel).toBe('2024-09 – 2025-07')
    expect(wins[0].startDate).toBe('2024-09-09')
    expect(wins[0].endDate).toBe('2025-07-20')
    expect(wins[0].isReturn).toBeCloseTo(0.22084, 5)
    expect(wins[0].osReturn).toBeCloseTo(1.221443, 5)
    expect(wins[0].isSharpe).toBeCloseTo(-2.859942, 4)
    expect(wins[0].osSharpe).toBeCloseTo(5.100604, 4)
    expect(wins[0].oosRatioRaw).toBeCloseTo(5.530893, 4)
    expect(wins[0].oosRatio).toBe(2) // display clamp at +2

    expect(wins[1].periodLabel).toBe('2024-11 – 2025-09')
    expect(wins[1].isReturn).toBeCloseTo(0.33126, 5)
    expect(wins[1].osReturn).toBe(0)
    expect(wins[1].isSharpe).toBeCloseTo(-1.140403, 4)
    expect(wins[1].osSharpe).toBeCloseTo(1.034128, 4)

    expect(wins[2].periodLabel).toBe('2025-01 – 2025-11')
    expect(wins[2].isReturn).toBeCloseTo(0.33126, 5)
    expect(wins[2].isSharpe).toBeCloseTo(0.563108, 4)
    expect(wins[2].osSharpe).toBeNull()
  })

  it('summary aggregates match the window pins exactly', () => {
    const sum = walkForwardSummary(walkForwardAnalysis('AAPL', 'Technology', wfRows()))
    expect(sum.avgIsReturn).toBeCloseTo(0.294453, 5)
    expect(sum.avgOsReturn).toBeCloseTo(0.407148, 5)
    expect(sum.avgIsSharpe).toBeCloseTo(-1.145746, 4)
    expect(sum.avgOsSharpe).toBeCloseTo(2.044911, 4)
    expect(sum.avgOosRatio).toBeCloseTo(0.666667, 5)
    expect(sum.overfittingIndex).toBe(0) // avgOs > avgIs → clamped at 0
  })

  it('too-short series yields no windows; empty summary is the exact sentinel', () => {
    expect(walkForwardAnalysis('AAPL', 'Technology', wfRows().slice(0, 500))).toHaveLength(0)
    expect(walkForwardSummary([])).toEqual({
      avgIsReturn: 0, avgOsReturn: 0, avgIsSharpe: null, avgOsSharpe: null,
      avgOosRatio: 0, overfittingIndex: 1, windows: [],
    })
  })
})

describe('computeOosRatio — exact clamp pins', () => {
  it('raw ratio and ±[−1, 2] display clamp', () => {
    expect(computeOosRatio(0.1, 0.05)).toEqual({ raw: 0.5, display: 0.5 })
    expect(computeOosRatio(0, 5)).toEqual({ raw: 0, display: 0 }) // zero-IS guard
    expect(computeOosRatio(0.01, 0.05)).toEqual({ raw: 5, display: 2 })
    expect(computeOosRatio(0.01, -0.05)).toEqual({ raw: -5, display: -1 })
  })
})

// ─── liveSignal — adapter goldens ────────────────────────────────────────────

describe('buildLiveInstrumentSignal — golden (production signal path)', () => {
  beforeEach(() => vi.stubEnv('QUANTAN_USE_ENHANCED_SIGNAL', '0'))

  it('dip-bar rows map to the exact API payload', () => {
    const live = buildLiveInstrumentSignal(dipBar301(), 'TST', 'Technology')
    expect(live).not.toBeNull()
    expect(live!.price).toBeCloseTo(211.979477, 5)
    expect(live!.changePct).toBeCloseTo(-35.744, 3)
    expect(live!.zone).toBe('FIRST_DIP')
    expect(live!.dipSignal).toBe('STRONG_DIP')
    expect(live!.deviationPct).toBeCloseTo(-7.029659, 4)
    expect(live!.slopePct).toBeCloseTo(0.080289, 5)
    expect(live!.slopePositive).toBe(true)
    expect(live!.rsi14).toBeCloseTo(12.108324, 4)
    expect(live!.atrPct).toBeCloseTo(4.709481, 4)
    expect(live!.action).toBe('BUY')
    expect(live!.confidence).toBe(90)
    expect(live!.KellyFraction).toBeCloseTo(0.15, 10)
    expect(live!.regimeColor).toBe(REGIME_COLORS.FIRST_DIP)
    expect(live!.regimeColor).toBe('#84cc16')
    expect(live!.candles).toBe(301)
    expect(live!.lastDate).toBe('2024-10-27')
    expect(live!.ticker).toBe('TST')
    expect(live!.sector).toBe('Technology')
  })

  it('returns null below 200 rows (exact boundary)', () => {
    const rows = dipBar301()
    expect(buildLiveInstrumentSignal(rows.slice(0, 199), 'TST', 'T')).toBeNull()
    expect(buildLiveInstrumentSignal(rows.slice(0, 200), 'TST', 'T')).not.toBeNull()
  })
})

// ─── benchmarkLabel — label-pipeline goldens ─────────────────────────────────

describe('runInstrumentLabelBenchmark — golden (production path)', () => {
  it('recovery-dip fixture: exact BUY count, WR, and per-trade label math', () => {
    const stats = runInstrumentLabelBenchmark('AAPL', 'Technology', dipRecover380(), {
      productionPath: true,
    })!
    expect(stats.bars).toBe(380)
    expect(stats.buySignals).toBe(21)
    expect(stats.wins).toBe(21)
    expect(stats.losses).toBe(0)
    expect(stats.winRate).toBe(1)
    expect(stats.netWinRate).toBe(1)
    expect(stats.avgReturn20d).toBeCloseTo(0.104896, 5)
    expect(stats.avgNetReturn20d).toBeCloseTo(0.102696, 5)
    expect(stats.bnhReturn).toBeCloseTo(2.143494, 5)
    expect(stats.trades).toHaveLength(21)
    expect(stats.trades[0]).toMatchObject({ zone: 'FIRST_DIP', barIndex: 300, date: '2024-10-27' })
    expect(stats.trades[0].grossReturn).toBeCloseTo(0.104896, 5)
    expect(stats.trades[0].netReturn).toBeCloseTo(0.102696, 5)
    expect(stats.trades[stats.trades.length - 1].barIndex).toBe(320)
    // net = gross minus the round-trip cost, always strictly below
    expect(stats.trades[0].netReturn).toBeLessThan(stats.trades[0].grossReturn)
  })

  it('signalAtBarIndex pins: BUY at the crash bar, HOLD pre-crash', () => {
    const rows = dipRecover380()
    const buy = signalAtBarIndex(rows, 300, 'AAPL', { productionPath: true })
    expect(buy.action).toBe('BUY')
    expect(buy.regimeZone).toBe('FIRST_DIP')
    expect(buy.grossReturn).toBeCloseTo(0.104896, 5)
    expect(buy.netReturn).toBeCloseTo(0.102696, 5)
    const hold = signalAtBarIndex(rows, 250, 'AAPL', { productionPath: true })
    expect(hold.action).toBe('HOLD')
  })

  it('returns null under 252 rows', () => {
    expect(runInstrumentLabelBenchmark('AAPL', 'T', dipRecover380().slice(0, 251))).toBeNull()
  })
})

// ─── signalHelpers — exact function pins ─────────────────────────────────────

describe('piecewiseRsiScore — exact breakpoint pins', () => {
  it('maps every segment and boundary exactly', () => {
    expect(piecewiseRsiScore(NaN)).toBe(0)
    expect(piecewiseRsiScore(25)).toBe(1.0)
    expect(piecewiseRsiScore(30)).toBe(1.0) // (50-30)/20 — continuous at 30
    expect(piecewiseRsiScore(40)).toBeCloseTo(0.5, 10)
    expect(piecewiseRsiScore(50)).toBe(0)
    expect(piecewiseRsiScore(55)).toBeCloseTo(-0.25, 10)
    expect(piecewiseRsiScore(70)).toBeCloseTo(-1.0, 10) // -(70-50)/20 — continuous at 70
    expect(piecewiseRsiScore(75)).toBe(-1.0)
  })
})

describe('isGoldenCross / hasPositiveMomentum / isMACompression — boundaries', () => {
  it('golden cross: EMA50 above EMA200 on a rising series, false on falling / short', () => {
    const rising = Array.from({ length: 250 }, (_, i) => 100 + i)
    const falling = Array.from({ length: 250 }, (_, i) => 350 - i)
    expect(isGoldenCross(rising)).toBe(true)
    expect(isGoldenCross(falling)).toBe(false)
    expect(isGoldenCross(rising.slice(0, 199))).toBe(false) // < 200 guard
  })

  it('momentum: strict > over exactly `period` bars back', () => {
    const rising = Array.from({ length: 64 }, (_, i) => 100 + i)
    expect(hasPositiveMomentum(rising)).toBe(true)
    expect(hasPositiveMomentum(rising.slice(0, 63))).toBe(false) // needs period+1
    expect(hasPositiveMomentum(Array.from({ length: 64 }, () => 100))).toBe(false) // flat, strict >
    expect(hasPositiveMomentum([100, 101, 102], 2)).toBe(true) // custom period
    expect(hasPositiveMomentum([102, 101, 100], 2)).toBe(false)
  })

  it('MA compression: flat ribbon compresses; steep trend does not; tolerance is strict <', () => {
    const flat = Array.from({ length: 240 }, () => 100)
    expect(isMACompression(flat)).toBe(true) // spread 0 < 0.05
    expect(isMACompression(flat, 0)).toBe(false) // 0 < 0 is false
    const steep = Array.from({ length: 240 }, (_, i) => 100 * Math.pow(1.01, i))
    expect(isMACompression(steep)).toBe(false)
    expect(isMACompression(flat.slice(0, 199))).toBe(false) // < 200 guard
  })
})

describe('detectBullishDivergence — crafted trough pins', () => {
  // Two price troughs (15 shallow, 25 deeper) inside the 20-bar lookback tail.
  const divCloses = (() => {
    const c = Array.from({ length: 30 }, () => 100)
    c[15] = 95; c[14] = 97; c[16] = 97
    c[25] = 90; c[24] = 93; c[26] = 93
    return c
  })()
  const divRsi = (() => {
    const r = divCloses.map(() => 50)
    r[15] = 25; r[25] = 40 // RSI higher low at the deeper price low
    return r
  })()

  it('price lower low + RSI higher low (< 65) → divergence', () => {
    expect(detectBullishDivergence(divCloses, divRsi)).toBe(true)
  })
  it('RSI second low at/above 65 → no divergence (soft cap)', () => {
    const r = [...divRsi]; r[25] = 66
    expect(detectBullishDivergence(divCloses, r)).toBe(false)
  })
  it('RSI lower low → no divergence', () => {
    const r = [...divRsi]; r[25] = 20
    expect(detectBullishDivergence(divCloses, r)).toBe(false)
  })
  it('price higher low → no divergence', () => {
    const c = [...divCloses]; c[25] = 96
    expect(detectBullishDivergence(c, divRsi)).toBe(false)
  })
  it('insufficient bars → false', () => {
    expect(detectBullishDivergence(divCloses.slice(0, 10), divRsi.slice(0, 10))).toBe(false)
  })
})

describe('detectVolumeClimax — crafted threshold pins', () => {
  function climaxBars(volMult: number, bodyPct: number, closeAboveMid: boolean) {
    const bars = Array.from({ length: 25 }, () => ({
      open: 100, high: 101, low: 99, close: 100, volume: 1000,
    }))
    bars[23] = { open: 100, high: 104, low: 96, close: 98, volume: 1000 } // prev mid = 100
    const open = 110
    const close = open * (1 - bodyPct)
    bars[24] = {
      open, high: 111, low: close - 1,
      close: closeAboveMid ? Math.max(close, 100.5) : Math.min(close, 99.5),
      volume: 1000 * volMult,
    }
    return bars
  }

  it('spike >2×, bearish body >1.5%, close above prev mid → climax', () => {
    expect(detectVolumeClimax(climaxBars(3, 0.05, true))).toBe(true)
  })
  it('volume EXACTLY 2× average is not a spike (strict >)', () => {
    expect(detectVolumeClimax(climaxBars(2, 0.05, true))).toBe(false)
  })
  it('body ≤1.5% is not a panic candle', () => {
    expect(detectVolumeClimax(climaxBars(3, 0.01, true))).toBe(false)
  })
  it('close below prev-range midpoint is not a recovery', () => {
    expect(detectVolumeClimax(climaxBars(3, 0.05, false))).toBe(false)
  })
})

describe('priceWasNearSmaRecently — threshold pins', () => {
  const farBelow = Array.from({ length: 240 }, (_, i) => (i < 200 ? 100 : 80))
  const flat = Array.from({ length: 240 }, () => 100)

  it('20% below SMA for the whole window → false at the default 5% threshold', () => {
    expect(priceWasNearSmaRecently(farBelow)).toBe(false)
  })
  it('flat at the SMA → true; < 220 bars → false; wide threshold flips the far case', () => {
    expect(priceWasNearSmaRecently(flat)).toBe(true)
    expect(priceWasNearSmaRecently(flat.slice(0, 219))).toBe(false)
    expect(priceWasNearSmaRecently(farBelow, 25)).toBe(true)
  })
})
